baseurl = "https://antefact.github.io/ghostchef_minisite/"
languageCode = "en-us"
title = "Ghost Chef üëªüç≥"
theme ="bxb"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All blog posts are defined in their own files.

	title = "Ghost Chef"
	subtitle = "A research on generative tools and food"

  [params.processGallery]
    [[params.processGallery.photos]]
    img = "sketching.jpg"
    captionTitle = "sketching Plates"
    captionDescription = "Chef use to design plates on paper"

    [[params.processGallery.photos]]
    img = "tasks.jpg"
    captionTitle = "task division"
    captionDescription = "every recipe is divided in microtasks,"

    [[params.processGallery.photos]]
    img = "centaurkitchen.png"
    captionTitle = "the centaur kitchen"
    captionDescription = ""

    [[params.processGallery.photos]]
    img = "centaurkitchen2.png"
    captionTitle = "# fried cicken"
    captionDescription = "deep fried chicken served with bacon flavoured chips"


  [params.interactionDetail]
    [params.interactionDetail.headerGif]
    name = "globalGIf"
    fileName = "topGif.gif"
    caption= "Just start interacting with ghostchef by writing in something. Feel free to start from an ingredient, a recipe, a combination or even an emotion."
    width=12

    [[params.interactionDetail.gifs]]
    name = "globalGIf"
    fileName = "gif2.gif"
    caption= "Decide who's going to be your ghost chef, which culinary identity should inspire you."
    width=6


    [[params.interactionDetail.gifs]]
    name = "globalGIf"
    fileName = "sliders.gif"
    caption= "Tweak the intelligence behaviour by adjusting each chef specific settings."
    width=6

    [[params.interactionDetail.gifs]]
    name = "globalGIf"
    fileName = "learning.gif"
    caption= "Teach the sysyem your style and record your personal culinary identity."
    width=6

    [[params.interactionDetail.gifs]]
    name = "globalGIf"
    fileName = "extensions.gif"
    caption= "Access premium features like plating and task management."
    width=6

    [[params.credits]]
    name = "bxb"
    logo = "bxb_logo.png"
    link= "http://www.bitsxbites.com"
    [[params.credits]]
    name = "Mill"
    logo = "mill-logo.png"
    link= "http://www.mill-intelligence.com"


  # Navigation
	[params.navigation]
		brand = "brand"

	[params.navigation.links]

  [params.navigation.links.blog]
		name     = "blog"
		link = "/blog"

  [params.navigation.links.services]
  	name     = "services"
  	link = "#services"
